# Generated by Django 2.2.4 on 2024-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='ed_date',
            new_name='end_edu',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='ex_date',
            new_name='end_job',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='exprience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='skils',
            new_name='skills',
        ),
        migrations.AddField(
            model_name='resume',
            name='start_edu',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='resume',
            name='start_job',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Other', 'Other')], max_length=10),
        ),
    ]
