# Generated by Django 2.2.4 on 2024-02-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20240228_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Bhojpuri', 'Bhojpuri'), ('Urdu', 'Urdu'), ('Punjabi', 'Punjabi'), ('Mathali', 'Mathali'), ('Marathi', 'Marathi')], max_length=20),
        ),
    ]
