# Generated by Django 2.2.4 on 2024-02-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20240228_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
