# Generated by Django 2.2.4 on 2024-02-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20240228_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ex_job',
            field=models.TextField(default='developer'),
        ),
    ]
