# Generated by Django 2.2.4 on 2024-02-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_resume_ex_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='about',
            field=models.TextField(default='I am a developer in full stack'),
        ),
    ]
