# Generated by Django 2.2.4 on 2024-03-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20240229_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='position',
            field=models.CharField(default='Gold', max_length=20),
        ),
    ]
