# Generated by Django 2.2.4 on 2024-03-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_resume_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='pic',
            new_name='image',
        ),
    ]
