# Generated by Django 2.2.4 on 2024-03-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20240304_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='resume',
            name='l_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
