# Generated by Django 2.2.4 on 2024-03-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20240304_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about',
            field=models.TextField(max_length=1500),
        ),
    ]
