# Generated by Django 2.2.4 on 2024-03-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20240304_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='project1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='project2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='project_link1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='project_link2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
