# Generated by Django 2.2.4 on 2024-03-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_auto_20240304_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='github_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedin_link',
            field=models.URLField(null=True),
        ),
    ]
